import { Choices } from './choices';

export const CHOICES: Array<Choices[]> = [
	   [{ id: 0, text :"Game Over", nextId:1}],
	   [{ id: 1, text: "Le suivre en haut des marches ?", nextId: 261},{ id: 1, text : "Tirer votre épée et l'attaquer ?", nextId:54}],
   	[{ id: 2, text :"Game Over", nextId:1}],
   	[{ id: 3, text : "Oui", nextId:322},{ id: 3, text: "Non", nextId: 120}],
   	[{ id: 4, text : "Vous souhaitez toujours entrer dans la caverne ! ", nextId:49},{ id: 4, text: "Vous préférez retourner au croisement", nextId: 93}],
   	[{ id: 5, text : "Vous placez sur votre tête la couronne d'or", nextId:333},{ id: 5, text : "Vous préférez quitter l'anfractuosité et monter les marches qui conduisent au sommet de la caverne", nextId:249}],
   	[{ id: 6, text : "Vous vous dirigez en hâte vers le nord", nextId:148}],
   	[{ id: 7, text : "Vous ecasez le dernier essaim et continuez votre progression", nextId:23}],
   	[{ id: 8, text : "Vous souhaitez rencontrer les personnages qui se chamaillent", nextId:317},{ id: 8, text : "Vous préférez vous cacher dans les buissons, au bord du chemin, pour les laisser passer sans être vu.", nextId:392}],
   	[{ id: 9, text : "!SUITE", nextId:176}],
   	[{ id: 10, text : "En poussant un juron, vous décidez de vous ruer sur l'Ogre pour l'attaquer.", nextId:290}],
   	[{ id: 11, text : "Vous faites quelques pas en vacillant, puis vous tombez évanoui sur le sol.", nextId:353}],
   	[{ id: 12, text : "Vous poursuivez la conversation avec le Gnome", nextId:271},{ id: 12, text : "Vous preferez reprendre votre chemin vers l'ouest", nextId:67}],
   	[{ id: 13, text : "Vous vous relevez parmi les ruines et vous regagnez à pas lents le chemin que vous allez suivre en direction du nord.", nextId:149}],
   	[{ id: 14, text : "Vous repartez vers le nord, le long du défilé", nextId:255}],
   	[{ id: 15, text : "!SUITE", nextId:217}],
   	[{ id: 16, text : "Oui", nextId:211},{ id: 16, text : "Non", nextId:345}],
   	[{ id: 17, text : "Vous jetez une Pièce d'Or !EVENT dans le puits et faite un vœu", nextId:89},{ id: 17, text : "Vous descendez l'échelle pour aller voir ce tunnel d'un peu plus près", nextId:256},{ id: 17, text : "Vous retournez sur le chemin et prenez la direction de l'ouest.", nextId:238}],
   	[{ id: 18, text : "Au matin, vous ramassez vos affaires et vous suivez en direction du nord le chemin qui part vers les collines.", nextId:198}],
   	[{ id: 19, text : "!SUITE", nextId:18}],
   	[{ id: 20, text : "Vous poursuivez dans la même direction", nextId:277}],
   	[{ id: 21, text : "Vous vous remettez en chemin dans la direction du nord.", nextId:226}],
   	[{ id: 22, text : "Vous quittez aussitôt la caverne pour continuer en direction du nord.", nextId:358}],
   	[{ id: 23, text : "Vous vous remettez en route en direction du cours d'eau que vous entendez couler un peu plus loin.", nextId:339}],
   	[{ id: 24, text : "Tirer votre épée et poursuivre les Pygmées ?", nextId:377},{ id: 24, text : "Poursuivre votre chemin en direction du nord ?", nextId:92}],
   	[{ id: 25, text : "Si vous voulez poursuivre vers le nord", nextId:369},{ id: 25, text : "Si vous préférez aller à l'ouest", nextId:56}],
   	[{ id: 26, text : "Le ramasser ? ", nextId:91},{ id: 26, text : "Abandonner vos recherches et reprendre votre chemin en direction du nord ?", nextId:220}],
   	[{ id: 27, text : "Vous êtes soulagé de voir que les arbres commencent à se clairsemer et qu'ils apparaissent moins menaçants.", nextId:329}],
   	[{ id: 28, text : "Oui", nextId:52},{ id: 28, text : "Non", nextId:266}],
   	[{ id: 29, text : "!SUITE", nextId:383},{ id: 29, text : "Si vous souhaitez prendre la Fuite pendant le combat, vous pouvez le faire en retournant sur le chemin que vous suivrez vers le nord.", nextId:254}],
   	[{ id: 30, text : "!SUITE", nextId:225}],
   	[{ id: 31, text : "Vous remontez à l air libre et vous rejoignez le chemin.", nextId:362}],
   	[{ id: 32, text : "Vous poursuivez votre route en direction du nord.", nextId:150}],
   	[{ id: 33, text : "Vous le regardez s'éloigner, puis vous reprenez votre chemin en direction du nord.", nextId:390}],
   	[{ id: 34, text : "Vous la jetez à terre et vous partez vers le nord.", nextId:231}],
   	[{ id: 35, text : "!SUITE", nextId:132}],
   	[{ id: 36, text : "Il ne vous reste donc plus qu'à le maudire et à poursuivre votre chemin vers le nord.", nextId:187}],
   	[{ id: 37, text : "Vous crachez ce que vous avez dans la bouche et poursuivez votre chemin vers le nord", nextId:226},{ id: 37, text : "Vous préférez manger le fruit.", nextId:336}],
   	[{ id: 38, text : "Vous souhaitez entrer dans la cabane", nextId:315},{ id: 38, text : "Vous préférez retourner sur le chemin et poursuivre vers le nord.", nextId:220}],
   	[{ id: 39, text : "Enfin, vous quittez la caverne en laissant le monstre se dépêtrer du filet.", nextId:287}],
   	[{ id: 40, text : "Vous poursuivez votre chemin vers le nord.", nextId:274}],
   	[{ id: 41, text : "Vous prenez à gauche et vous courez vers l'est en criant Bon après-midi ! au corbeau, lorsque vous passez devant lui.", nextId:239}],
   	[{ id: 42, text : "Puis vous tirez votre épée", nextId:342}],
   	[{ id: 43, text : "!SUITE", nextId:50},{ id: 43, text : "Vous fuyez vers le nord", nextId:188}],
   	[{ id: 44, text : "Vous vous dirigez vers les marches, dans le mur du fond", nextId:293}],
   	[{ id: 45, text : "!SUITE", nextId:165}],
   	[{ id: 46, text : "Vous décidez de traiter le Gnome avec un peu plus de respect en commençant par lui présenter vos excuses.", nextId:12}],
   	[{ id: 47, text : "Fouiller la cabane en quête de quelque chose qui pourrait vous être utile.", nextId:26},{ id: 47, text : "Quitter la cabane et revenir sur le chemin pour poursuivre vers le nord", nextId:220}],
   	[{ id: 48, text : "Vous quittez la pièce d'un pas chancelant et vous poursuivez votre chemin en direction du nord.", nextId:288}],
   	[{ id: 49, text : "!SUITE", nextId:371}],
   	[{ id: 50, text : "Puis vous repartez vers le nord.", nextId:188}],
   	[{ id: 51, text : "Vous prenez la direction du Nord", nextId:199},{ id: 51, text : "Vous continuez vers l'est", nextId:397}],
   	[{ id: 52, text : "Vous poursuivez votre effort et vous lui plaquez le bras contre la table : il est vaincu.", nextId:78}],
   	[{ id: 53, text : "Vous brandissez le poing dans un geste de rage envers ces voleurs invisibles et vous reprenez votre route en direction du nord.", nextId:92}],
   	[{ id: 54, text : "L'attaquer", nextId:399},{ id: 54, text : "Vous changez d'avis et le suivez en haut des marches", nextId:261}],
   	[{ id: 55, text : "Examiner d'un peu plus près cette créature dans sa cage?", nextId:168},{ id: 55, text : "Fouiller la caverne?", nextId:313},{ id: 55, text : "Quitter la caverne et repartir vers le nord ?", nextId:358}],
   	[{ id: 56, text : "Vous poursuivez vers l'ouest.", nextId:233},{ id: 56, text : "Vous préférez prendre la direction du nord.", nextId:163}],
   	[{ id: 57, text : "Si vous êtes Chanceux, le jet de feu vous manque et vient frapper le sol à vos pieds.", nextId:132},{ id: 57, text : "Si vous êtes Malchanceux, les flammes s'abattent sur vous et vous êtes précipité à terre.", nextId:35}],
   	[{ id: 58, text : "Vous remontez l'escalier pour quitter la crypte et reprendre votre chemin vers le nord.", nextId:112}],
   	[{ id: 59, text : "Vous décidez de poursuivre vers l'est sans chercher à suivre le chemin orienté au sud.", nextId:171}],
   	[{ id: 60, text : "Si vous êtes Chanceux, vous les trouvez tout de suite et vous les glissez aussitôt dans vos narines.", nextId:183},{ id: 60, text : "Si vous êtes Malchanceux, en revanche, vous n'arrivez pas à mettre la main dessus suffisamment vite et vous ne pouvez vous empêcher de respirer le gaz empoisonné.", nextId:44}],
   	[{ id: 61, text : "Si vous désirez ramper en direction du sud pour retourner au puits.", nextId:398},{ id: 61, text : "Si vous préférez poursuivre vers l'est.", nextId:151}],
   	[{ id: 62, text : "Vous faites alors volte-face et vous repartez vers l'ouest.", nextId:208}],
   	[{ id: 63, text : "Vous rengainez aussitôt votre épée et vous décidez de traverser la rivière à pied.", nextId:178}],
   	[{ id: 64, text : "Vous décidez alors de vous enfuir à toutes jambes tant que durent les effets de la Potion.", nextId:142}],
   	[{ id: 65, text : "C'est là que vous avez décidé de passer la nuit, votre épée à portée de la main.", nextId:330}],
   	[{ id: 66, text : "Vous allumez un feu de camp et vous vous couchez bientôt, votre épée au côté.", nextId:325}],
   	[{ id: 67, text : "Vous décidez donc de poursuivre vers l'ouest.", nextId:113}],
   	[{ id: 68, text : "Vous vous remettez en route en prenant la direction de l'est.", nextId:59}],
   	[{ id: 69, text : "Attaquer l'un des petits humanoïdes ?", nextId:264},{ id: 69, text : "Couper un champignon avec votre épée?", nextId:143},{ id: 69, text : "Demander à goûter un des champignons à chapeaux verts?", nextId:269},{ id: 69, text : "Demander à goûter un des champignons à chapeaux rouges?", nextId:16}],
   	[{ id: 70, text : "Vous repartez vers le nord, le long du défilé.", nextId:334}],
   	[{ id: 71, text : "!SUITE", nextId:273}],
   	[{ id: 72, text : "Vous décidez donc de poursuivre en direction du nord.", nextId:138}],
   	[{ id: 73, text : "Vous retournez sur le chemin pour prendre la direction du nord.", nextId:112}],
   	[{ id: 74, text : "Vous revenez à la bifurcation pour prendre le chemin qui mène vers le nord.", nextId:1}],
   	[{ id: 75, text : "Quelques instants plus tard, vous vous apprêtez à vous endormir, votre épée à portée de main.", nextId:330}],
   	[{ id: 76, text : "Le chemin oblique brusquement vers la droite et continue en direction du nord à travers d'épaisses broussailles.", nextId:206}],
   	[{ id: 77, text : "Tirer votre épée et les poursuivre ?", nextId:377},{ id: 77, text : "Poursuivre votre chemin vers le nord ?", nextId:92}],
   	[{ id: 78, text : "Vous quittez ensuite la cabane et vous revenez à la bifurcation.", nextId:349}],
   	[{ id: 79, text : "!SUITE", nextId:386}],
   	[{ id: 80, text : "Vous vous dirigez vers les marches, dans la paroi du fond.", nextId:293}],
   	[{ id: 81, text : "Si vous êtes Chanceux, la flèche vous siffle aux oreilles sans vous atteindre.", nextId:49},{ id: 81, text : "Si vous êtes Malchanceux, la flèche vient se planter dans votre épaule.", nextId:4}],
   	[{ id: 82, text : "Oui", nextId:235},{ id: 82, text : "Non", nextId:13}],
   	[{ id: 83, text : "!SUITE", nextId:139}],
   	[{ id: 84, text : "!SUITE", nextId:146},{ id: 84, text : "!FUITE", nextId:245}],
   	[{ id: 85, text : "Si vous souhaitez ouvrir la porte de la cage.", nextId:9},{ id: 85, text : "Si vous préférez ne pas vous occuper de cette créature et quitter la caverne pour poursuivre votre chemin vers le nord.", nextId:358}],
   	[{ id: 86, text : "Puis, avec une pensée pour le malheureux renard ainsi poursuivi, vous repartez vers le nord.", nextId:208}],
   	[{ id: 87, text : "Vous décidez donc de poursuivre vers le nord.", nextId:90}],
   	[{ id: 88, text : "Si vous souhaitez pénétrer dans cette anfractuosité.", nextId:212},{ id: 88, text : "Si vous préférez continuer à monter les marches.", nextId:107}],
   	[{ id: 89, text : "Descendre l'échelle pour explorer le tunnel, au fond du puits?", nextId:256},{ id: 89, text : "Retourner sur le chemin pour aller vers l'est ? ", nextId:281},{ id: 89, text : "Retourner sur le chemin pour aller vers l'ouest ? ", nextId:238}],
   	[{ id: 90, text : "Si vous êtes Chanceux, la flèche vous manque", nextId:210},{ id: 90, text : "Si vous êtes Malchanceux, la flèche vient se planter dans votre épaule et vous perdez 3 points d'ENDURANCE. !EVENT", nextId:348}],
   	[{ id: 91, text : "Vous quittez ensuite la caverne, puis vous rejoignez le chemin pour prendre la direction du nord.", nextId:220}],
   	[{ id: 92, text : "Vous enfuir à toutes jambes pour essayer d'atteindre le cours d'eau un peu plus loin ?", nextId:299},{ id: 92, text : "Faire face et combattre ?", nextId:7},{ id: 92, text : "Boire une Potion de Contrôle des Insectes ? (si vous en avez une, bien entendu). !EVENT", nextId:100}],
   	[{ id: 93, text : "Vous pouvez soit aller à l'est.", nextId:61},{ id: 93, text : "Soit poursuivre en direction du sud.", nextId:270}],
   	[{ id: 94, text : "Si vous souhaitez suivre cette voie", nextId:136},{ id: 94, text : "Si vous préférez rejoindre le sentier et repartir vers le nord.", nextId:144}],
   	[{ id: 95, text : "Oui", nextId:173},{ id: 95, text : "Non", nextId:368}],
   	[{ id: 96, text : "!MONSTRE", nextId:62}],
   	[{ id: 97, text : "Si vous souhaitez vous asseoir sur cette chaise pour vous reposer et prendre quelque nourriture", nextId:328},{ id: 97, text : "Si vous préférez poursuivre vers le nord.", nextId:118}],
   	[{ id: 98, text : "Si vous êtes Chanceux, vous parvenez à vous échapper sans être atteint par les flèches qui tombent en pluie autour de vous", nextId:1},{ id: 98, text : " Mais si vous êtes Malchanceux, vous glissez dans votre fuite et vous mourez criblé de flèches, ce qui, bien entendu, met fin à votre aventure.", nextId:0}],
   	[{ id: 99, text : "Si vous souhaitez entrer dans la cabane", nextId:209},{ id: 99, text : "Si vous préférez retourner à la bifurcation", nextId:349}],
   	[{ id: 100, text : "Il ne vous reste plus qu'à poursuivre votre chemin vers le nord, en direction du bruit d'eau courante.", nextId:339}],
   	[{ id: 101, text : "Puis vous revenez à la bifurcation, et vous poursuivez vers le nord.", nextId:25}],
   	[{ id: 102, text : "Vous décidez, quant à vous, d'aller vers le nord.", nextId:105}],
   	[{ id: 103, text : "Si vous souhaitez aller voir de plus près de quoi il s'agit.", nextId:57},{ id: 103, text : "Si vous préférez vous hâter en direction du nord.", nextId:360}],
   	[{ id: 104, text : "!SUITE", nextId:311}],
   	[{ id: 105, text : "Si vous souhaitez quitter le chemin pour aller voir ce qui intéresse tant les vautours.", nextId:384},{ id: 105, text : " Si vous préférez laisser les charognards sans vous en occuper, vous poursuivrez votre chemin vers le nord.", nextId:394}],
   	[{ id: 106, text : "Vous quittez les lieux pour continuer vers le nord.", nextId:288}],
   	[{ id: 107, text : "!SUITE", nextId:152}],
   	[{ id: 108, text : "Vous repartez en direction du nord.", nextId:226}],
   	[{ id: 109, text : "Si vous voulez aller vers l'ouest.", nextId:124},{ id: 109, text : "Si vous voulez aller à l'est.", nextId:72},{ id: 109, text : "Si vous préférez poursuivre vers le nord.", nextId:309}],
   	[{ id: 110, text : "Si vous souhaitez fouiller le sac à dos en cuir du Gremlin", nextId:257},{ id: 110, text : "Si vous préférez quitter le tunnel sans plus attendre.", nextId:31}],
   	[{ id: 111, text : "Vous retournez à la bifurcation pour reprendre la direction du nord.", nextId:150}],
   	[{ id: 112, text : "Consultant alors la carte de Gromollet, vous décidez de reprendre la direction du nord qui mène à Pont-de-Pierre, sans vous occuper du sentier étroit continuant vers l'est.", nextId:103}],
   	[{ id: 113, text : "Si vous voulez aller jeter un coup d'oeil à la cabane.", nextId:324},{ id: 113, text : " Si vous préférez ne pas vous en occuper et continuer en direction du nord.", nextId:149}],
   	[{ id: 114, text : "Si vous avez des Capsules de Feu", nextId:350},{ id: 114, text : "Sinon, tirez votre épée.", nextId:123}],
   	[{ id: 115, text : "Si vous souhaitez aller vers l'ouest.", nextId:382},{ id: 115, text : "Si vous préférez prendre la direction de l'est.", nextId:277}],
   	[{ id: 116, text : "Puis vous rassemblez vos affaires, et vous repartez vers le nord.", nextId:314}],
   	[{ id: 117, text : "!SUITE", nextId:232}],
   	[{ id: 118, text : "!SUITE", nextId:174}],
   	[{ id: 119, text : "Vous pouvez soit continuer vers le nord en descendant la colline.", nextId:90},{ id: 119, text : "Soit suivre le sentier qui mène en direction de l'ouest.", nextId:216}],
   	[{ id: 120, text : "Oui", nextId:94},{ id: 120, text : "Non", nextId:380}],
   	[{ id: 121, text : "Vous pouvez soit aller vers l'est.", nextId:61},{ id: 121, text : "Soit continuer vers le nord.", nextId:81}],
   	[{ id: 122, text : "Si vous souhaitez vous engager à quatre pattes dans ce tunnel.", nextId:135},{ id: 122, text : "Si vous préférez remonter l'échelle et retourner sur le chemin.", nextId:362}],
   	[{ id: 123, text : "!SUITE", nextId:27},{ id: 123, text : " Vous avez toutefois le droit de fuir en retournant à la bifurcation sur le chemin.", nextId:234}],
   	[{ id: 124, text : "Vous décidez donc de continuer en direction du nord.", nextId:180}],
   	[{ id: 125, text : "Si vous souhaitez alors ressortir du trou et reprendre votre chemin vers le nord.", nextId:337},{ id: 125, text : "Si vous préférez continuer à descendre dans le trou.", nextId:15}],
   	[{ id: 126, text : "Si vous possédez des Filtres à Nez !EVENT", nextId:365},{ id: 126, text : "!SUITE", nextId:22}],
   	[{ id: 127, text : "Vous décidez alors de camper sous un grand et vieux chêne, à droite du chemin, et vous vous installez pour dormir, votre épée à portée de main.", nextId:298}],
   	[{ id: 128, text : "!SUITE", nextId:272}],
   	[{ id: 129, text : "Vous retournez ensuite à la bifurcation", nextId:349}],
   	[{ id: 130, text : "Si vous voulez tirer votre épée pour combattre cette FEMME FÉLINE", nextId:153},{ id: 130, text : "Si vous préférez vous enfuir à toutes jambes droit devant vous, déduisez 1 point de votre total de CHANCE !EVENT", nextId:355}],
   	[{ id: 131, text : "Vous allumez un feu et vous vous installez pour dormir, votre épée à portée de main.", nextId:325}],
   	[{ id: 132, text : "Oui", nextId:258},{ id: 132, text : "Non", nextId:167}],
   	[{ id: 133, text : "Si vous souhaitez essayer le gantelet.", nextId:374},{ id: 133, text : "Si vous préférez ne pas vous en occuper (ou si vous l'avez déjà essayé), repartez vers le nord, le long du chemin !EVENT", nextId:360}],
   	[{ id: 134, text : "Si vous voulez frotter vos blessures avec de la boue chaude", nextId:283},{ id: 134, text : "Si vous souhaitez vous remettre en route en direction du nord", nextId:303}],
   	[{ id: 135, text : "Si vous souhaitez ramper vers l'ouest", nextId:284},{ id: 135, text : "Si vous préférez ramper vers l est", nextId:151}],
   	[{ id: 136, text : "Pour l'explorer, il va donc falloir avancer à quatre pattes.", nextId:69}],
   	[{ id: 137, text : "Oui", nextId:55},{ id: 137, text : "Non", nextId:10}],
   	[{ id: 138, text : "!SUITE", nextId:64},{ id: 138, text : "Sinon", nextId:159}],
   	[{ id: 139, text : "Au matin, vous ramassez vos affaires et vous repartez vers le nord, sur le chemin qui mène en direction des collines.", nextId:198}],
   	[{ id: 140, text : "Vous pouvez soit continuer vers le nord en descendant la colline", nextId:25},{ id: 140, text : "Soit prendre l'embranchement qui mène en direction de l'est ", nextId:267}],
   	[{ id: 141, text : "Si vous souhaitez attaquer Gayemainar", nextId:347},{ id: 141, text : "Si vous préférez lui dire que vous ne pouvez lui être d'aucune aide, prenez congé de lui et poursuivez votre chemin vers l'est", nextId:59}],
   	[{ id: 142, text : "Engager la conversation avec lui ?", nextId:366},{ id: 142, text : "Le contourner et traverser la rivière à pied ?", nextId:178},{ id: 142, text : "Tirer votre épée et l'attaquer ?", nextId:251}],
   	[{ id: 143, text : "!SUITE", nextId:80}],
   	[{ id: 144, text : "Si vous souhaitez prendre la direction de l'ouest.", nextId:213},{ id: 144, text : "Si vous préférez en revanche aller vers l’est.", nextId:387}],
   	[{ id: 145, text : "Vous allumez un grand feu et vous vous couchez, votre épée à portée de la main.", nextId:285}],
   	[{ id: 146, text : "A présent, vous retournez sur le chemin, et vous repartez vers le nord, en direction de la vallée.", nextId:245}],
   	[{ id: 147, text : "Si vous souhaitez jeter un coup d'œil par la fenêtre de la cabane", nextId:38},{ id: 147, text : "Si vous préférez poursuivre vers le nord", nextId:220}],
   	[{ id: 148, text : "Si vous désirez poursuivre en direction du nord", nextId:97},{ id: 148, text : "Si vous préférez aller vers l'ouest", nextId:20}],
   	[{ id: 149, text : "Si vous voulez aller vers l'est", nextId:130},{ id: 149, text : " Si vous préférez, en revanche, prendre la direction du nord", nextId:306}],
   	[{ id: 150, text : "Si vous souhaitez prendre la direction de l'ouest", nextId:357},{ id: 150, text : "Si, en revanche, vous préférez aller à l'ouest", nextId:171}],
   	[{ id: 151, text : "A remp lir", nextId:71},{ id: 151, text : "A remp lir", nextId:296}],
   	[{ id: 152, text : "A remplir", nextId:333},{ id: 152, text : "A remplir", nextId:5},{ id: 152, text : "A remplir", nextId:249}],
   	[{ id: 153, text : "A remplir", nextId:202},{ id: 153, text : "A remplir", nextId:355}],
   	[{ id: 154, text : "A remplir", nextId:231}],
   	[{ id: 155, text : "A remplir", nextId:83},{ id: 155, text : "A remplir", nextId:259}],
   	[{ id: 156, text : "A remplir", nextId:109}],
   	[{ id: 157, text : "A remplir", nextId:125},{ id: 157, text : "A remplir", nextId:337}],
   	[{ id: 158, text : "A remplir", nextId:47},{ id: 158, text : "A remplir", nextId:353}],
   	[{ id: 159, text : "A remplir", nextId:142}],
   	[{ id: 160, text : "Payer au corbeau le prix qu'il demande pour son conseil ?", nextId:343},{ id: 160, text : "Ne pas vous occuper de l'oiseau et poursuivre votre chemin vers le nord?", nextId:8},{ id: 160, text : "Ne pas vous occuper de l'oiseau et prendre la direction de l'est ?", nextId:239}],
   	[{ id: 161, text : "A remplir", nextId:185},{ id: 161, text : "A remplir", nextId:341}],
   	[{ id: 162, text : "A remplir", nextId:285}],
   	[{ id: 163, text : "A remplir", nextId:375}],
   	[{ id: 164, text : "A remplir", nextId:144}],
   	[{ id: 165, text : "A remplir", nextId:242}],
   	[{ id: 166, text : "A remplir", nextId:390}],
   	[{ id: 167, text : "A remplir", nextId:305}],
   	[{ id: 168, text : "A remplir", nextId:117},{ id: 168, text : "A remplir", nextId:358}],
   	[{ id: 169, text : "A remplir", nextId:85},{ id: 169, text : "A remplir", nextId:358}],
   	[{ id: 170, text : "A remplir", nextId:223},{ id: 170, text : "A remplir", nextId:346}],
   	[{ id: 171, text : "A remplir", nextId:190}],
   	[{ id: 172, text : "A remplir", nextId:89},{ id: 172, text : "A remplir", nextId:256},{ id: 172, text : "A remplir", nextId:281}],
   	[{ id: 173, text : "A remplir", nextId:58},{ id: 173, text : "A remplir", nextId:227}],
   	[{ id: 174, text : "A remplir", nextId:323}],
   	[{ id: 175, text : "A remplir", nextId:372},{ id: 175, text : "A remplir", nextId:106}],
   	[{ id: 176, text : "A remplir", nextId:358}],
   	[{ id: 177, text : "Aller vers l'ouest", nextId:289},{ id: 177, text : "Aller vers l'est", nextId:160}],
   	[{ id: 178, text : "A remplir", nextId:298}],
   	[{ id: 179, text : "A remplir", nextId:115}],
   	[{ id: 180, text : "A remplir", nextId:105},{ id: 180, text : "A remplir", nextId:361}],
   	[{ id: 181, text : "A remplir", nextId:162}],
   	[{ id: 182, text : "A remplir", nextId:70},{ id: 182, text : "A remplir", nextId:334}],
   	[{ id: 183, text : "A remplir", nextId:293}],
   	[{ id: 184, text : "A remplir", nextId:390}],
   	[{ id: 185, text : "A remplir", nextId:250},{ id: 185, text : "A remplir", nextId:149}],
   	[{ id: 186, text : "A remplir", nextId:0}],
   	[{ id: 187, text : "A remplir", nextId:286},{ id: 187, text : "A remplir", nextId:203},{ id: 187, text : "A remplir", nextId:6}],
   	[{ id: 188, text : "A remplir", nextId:221},{ id: 188, text : "A remplir", nextId:359}],
   	[{ id: 189, text : "A remplir", nextId:269},{ id: 189, text : "A remplir", nextId:293}],
      [{ id: 190, text : "A remplir", nextId:265},{ id: 190, text : "A remplir", nextId:318}],
   	[{ id: 191, text : "A remplir", nextId:184},{ id: 191, text : "A remplir", nextId:243}],
   	[{ id: 192, text : "A remplir", nextId:12},{ id: 192, text : "A remplir", nextId:46}],
   	[{ id: 193, text : "A remplir", nextId:110}],
   	[{ id: 194, text : "A remplir", nextId:208}],
   	[{ id: 195, text : "A remplir", nextId:352},{ id: 195, text : "A remplir", nextId:156}],
   	[{ id: 196, text : "A remplir", nextId:376},{ id: 196, text : "A remplir", nextId:39},{ id: 196, text : "A remplir", nextId:25}],
   	[{ id: 197, text : "A remplir", nextId:24},{ id: 197, text : "A remplir", nextId:53}],
   	[{ id: 198, text : "A remplir", nextId:278},{ id: 198, text : "A remplir", nextId:87}],
   	[{ id: 199, text : "A remplir", nextId:134},{ id: 199, text : "A remplir", nextId:283},{ id: 199, text : "A remplir", nextId:303}],
   	[{ id: 200 ,text: "200", nextId:351},{ id: 200 ,text: "200", nextId:112}],
      [{ id: 201 ,text: "XXX", nextId:389},{ id: 201 ,text: "XXX", nextId:88}],
      [{ id: 202 ,text: "XXX", nextId:355}],
      [{ id: 203 ,text: "XXX", nextId:373}],
      [{ id: 204 ,text: "XXX", nextId:400},{ id: 204 ,text: "XXX", nextId:381}],
      [{ id: 205 ,text: "XXX", nextId:92}],
      [{ id: 206 ,text: "XXX", nextId:253},{ id: 206 ,text: "XXX", nextId:187}],
      [{ id: 207 ,text: "XXX", nextId:302},{ id: 207 ,text: "XXX", nextId:109}],
      [{ id: 208 ,text: "XXX", nextId:99},{ id: 208 ,text: "XXX", nextId:291}],
      [{ id: 209 ,text: "XXX", nextId:28},{ id: 209 ,text: "XXX", nextId:349}],
      [{ id: 210 ,text: "XXX", nextId:43},{ id: 210 ,text: "XXX", nextId:188}],
      [{ id: 211 ,text: "XXX", nextId:293}],
      [{ id: 212 ,text: "XXX", nextId:321},{ id: 212 ,text: "XXX", nextId:107}],
      [{ id: 213 ,text: "XXX", nextId:306}],
      [{ id: 214 ,text: "XXX", nextId:69}],
      [{ id: 215 ,text: "XXX", nextId:248},{ id: 215 ,text: "XXX", nextId:201}],
      [{ id: 216 ,text: "XXX", nextId:278}],
      [{ id: 217 ,text: "XXX", nextId:262},{ id: 217 ,text: "XXX", nextId:337}],
      [{ id: 218 ,text: "XXX", nextId:274}],
      [{ id: 219 ,text: "XXX", nextId:300}],
      [{ id: 220 ,text: "XXX", nextId:275},{ id: 220 ,text: "XXX", nextId:115}],
      [{ id: 221 ,text: "XXX", nextId:378},{ id: 221 ,text: "XXX", nextId:199}],
      [{ id: 222 ,text: "XXX", nextId:293}],
      [{ id: 223 ,text: "XXX", nextId:150}],
      [{ id: 224 ,text: "XXX", nextId:332}],
      [{ id: 225 ,text: "XXX", nextId:135},{ id: 225 ,text: "XXX", nextId:362}],
      [{ id: 226 ,text: "XXX", nextId:29},{ id: 226 ,text: "XXX", nextId:254}],
      [{ id: 227 ,text: "XXX", nextId:312},{ id: 227 ,text: "XXX", nextId:2}],
      [{ id: 228 ,text: "XXX", nextId:255}],
      [{ id: 229 ,text: "XXX", nextId:165},{ id: 229 ,text: "XXX", nextId:45}],
      [{ id: 230 ,text: "XXX", nextId:137},{ id: 230 ,text: "XXX", nextId:290},{ id: 230 ,text: "XXX", nextId:358}],
      [{ id: 231 ,text: "XXX", nextId:224},{ id: 231 ,text: "XXX", nextId:332}],
      [{ id: 232 ,text: "XXX", nextId:263},{ id: 232 ,text: "XXX", nextId:358}],
      [{ id: 233 ,text: "XXX", nextId:17},{ id: 233 ,text: "XXX", nextId:238}],
      [{ id: 234 ,text: "XXX", nextId:382}],
      [{ id: 235 ,text: "XXX", nextId:149}],
      [{ id: 236 ,text: "XXX", nextId:170},{ id: 236 ,text: "XXX", nextId:150}],
      [{ id: 237 ,text: "XXX", nextId:214},{ id: 237 ,text: "XXX", nextId:304}],
      [{ id: 238 ,text: "XXX", nextId:221}],
      [{ id: 239 ,text: "XXX", nextId:37},{ id: 239 ,text: "XXX", nextId:226}],
      [{ id: 240 ,text: "XXX", nextId:338},{ id: 240 ,text: "XXX", nextId:169}],
      [{ id: 241 ,text: "XXX", nextId:219}],
      [{ id: 242 ,text: "XXX", nextId:121}],
      [{ id: 243 ,text: "XXX", nextId:166},{ id: 243 ,text: "XXX", nextId:33}],
      [{ id: 244 ,text: "XXX", nextId:198}],
      [{ id: 245 ,text: "XXX", nextId:163},{ id: 245 ,text: "XXX", nextId:233},{ id: 245 ,text: "XXX", nextId:393}],
      [{ id: 246 ,text: "XXX", nextId:204}],
      [{ id: 247 ,text: "XXX", nextId:3},{ id: 247 ,text: "XXX", nextId:144}],
      [{ id: 248 ,text: "XXX", nextId:389},{ id: 248 ,text: "XXX", nextId:88}],
      [{ id: 249 ,text: "XXX", nextId:164}],
      [{ id: 250, text : "!SUITE", nextId:82}],
      [{ id: 251 ,text: "XXX", nextId:63},{ id: 251 ,text: "XXX", nextId:260}],
      [{ id: 252 ,text: "XXX", nextId:309},{ id: 252 ,text: "XXX", nextId:72}],
      [{ id: 253 ,text: "XXX", nextId:344},{ id: 253 ,text: "XXX", nextId:187}],
      [{ id: 254 ,text: "XXX", nextId:241},{ id: 254 ,text: "XXX", nextId:300}],
      [{ id: 255 ,text: "XXX", nextId:182},{ id: 255 ,text: "XXX", nextId:334}],
      [{ id: 256 ,text: "XXX", nextId:122},{ id: 256 ,text: "XXX", nextId:295}],
      [{ id: 257 ,text: "XXX", nextId:31}],
      [{ id: 258 ,text: "XXX", nextId:305}],
      [{ id: 259 ,text: "XXX", nextId:244},{ id: 259 ,text: "XXX", nextId:19}],
      [{ id: 260 ,text: "260", nextId:178}],
      [{ id: 261, text : "Vous remerciez Yaztromo et vous quittez la pièce en redescendant l'escalier en colimaçon", nextId:177}],
      [{ id: 262 ,text: "262", nextId:337}],
      [{ id: 263 ,text: "XXX", nextId:126},{ id: 263 ,text: "XXX", nextId:358}],
      [{ id: 264 ,text: "XXX", nextId:367},{ id: 264 ,text: "XXX", nextId:189},{ id: 264 ,text: "XXX", nextId:282}],
      [{ id: 265 ,text: "XXX", nextId:356}],
      [{ id: 266 ,text: "XXX", nextId:354},{ id: 266 ,text: "XXX", nextId:129}],
      [{ id: 267 ,text: "XXX", nextId:25}],
      [{ id: 268 ,text: "XXX", nextId:119}],
      [{ id: 269 ,text: "XXX", nextId:293}],
      [{ id: 270 ,text: "XXX", nextId:229},{ id: 270 ,text: "XXX", nextId:121}],
      [{ id: 271 ,text: "XXX", nextId:297},{ id: 271 ,text: "XXX", nextId:67}],
      [{ id: 272 ,text: "XXX", nextId:394}],
      [{ id: 273 ,text: "XXX", nextId:296}],
      [{ id: 274 ,text: "XXX", nextId:195},{ id: 274 ,text: "XXX", nextId:109}],
      [{ id: 275 ,text: "XXX", nextId:179},{ id: 275 ,text: "XXX", nextId:115}],
      [{ id: 276 ,text: "XXX", nextId:62}],
      [{ id: 277 ,text: "XXX", nextId:234},{ id: 277 ,text: "XXX", nextId:114}],
      [{ id: 278 ,text: "XXX", nextId:319},{ id: 278 ,text: "XXX", nextId:319}],
      [{ id: 279 ,text: "XXX", nextId:246}],
      [{ id: 280 ,text: "XXX", nextId:306}],
      [{ id: 281 ,text: "XXX", nextId:163},{ id: 281 ,text: "XXX", nextId:393}],
      [{ id: 282 ,text: "XXX", nextId:293}],
      [{ id: 283 ,text: "XXX", nextId:303}],
      [{ id: 284 ,text: "XXX", nextId:81},{ id: 284 ,text: "XXX", nextId:270}],
      [{ id: 285 ,text: "XXX", nextId:388}],
      [{ id: 286 ,text: "XXX", nextId:373}],
      [{ id: 287 ,text: "XXX", nextId:25}],
      [{ id: 288 ,text: "XXX", nextId:84},{ id: 288 ,text: "XXX", nextId:245}],
      [{ id: 289 ,text: "XXX", nextId:76},{ id: 289 ,text: "XXX", nextId:147}],
      [{ id: 290 ,text: "XXX", nextId:385},{ id: 290 ,text: "XXX", nextId:358}],
      [{ id: 291 ,text: "XXX", nextId:335},{ id: 291 ,text: "XXX", nextId:145}],
      [{ id: 292 ,text: "XXX", nextId:95},{ id: 292 ,text: "XXX", nextId:112}],
      [{ id: 293 ,text: "XXX", nextId:215},{ id: 293 ,text: "XXX", nextId:389},{ id: 293 ,text: "XXX", nextId:88}],
      [{ id: 294 ,text: "XXX", nextId:106},{ id: 294 ,text: "XXX", nextId:175},{ id: 294 ,text: "XXX", nextId:288}],
      [{ id: 295 ,text: "XXX", nextId:225},{ id: 295 ,text: "XXX", nextId:30}],
      [{ id: 296 ,text: "XXX", nextId:398},{ id: 296 ,text: "XXX", nextId:284}],
      [{ id: 297 ,text: "XXX", nextId:67}],
      [{ id: 298 ,text: "XXX", nextId:140}],
      [{ id: 299 ,text: "XXX", nextId:75}],
      [{ id: 300 ,text: "XXX", nextId:138},{ id: 300 ,text: "XXX", nextId:331}],
      [{ id: 301 ,text: "XXX", nextId:157}],
      [{ id: 302 ,text: "XXX", nextId:109}],
      [{ id: 303 ,text: "XXX", nextId:247}],
      [{ id: 304 ,text: "XXX", nextId:69}],
      [{ id: 305 ,text: "XXX", nextId:374},{ id: 305 ,text: "XXX", nextId:133},{ id: 305 ,text: "XXX", nextId:360}],
      [{ id: 306 ,text: "XXX", nextId:391},{ id: 306 ,text: "XXX", nextId:112}],
      [{ id: 307 ,text: "XXX", nextId:192},{ id: 307 ,text: "XXX", nextId:271}],
      [{ id: 308 ,text: "XXX", nextId:148}],
      [{ id: 309 ,text: "XXX", nextId:77},{ id: 309 ,text: "XXX", nextId:197}],
      [{ id: 310 ,text: "XXX", nextId:101}],
      [{ id: 311 ,text: "XXX", nextId:204}],
      [{ id: 312 ,text: "XXX", nextId:112}],
      [{ id: 313 ,text: "XXX", nextId:240},{ id: 313 ,text: "XXX", nextId:85},{ id: 313 ,text: "XXX", nextId:358}],
      [{ id: 314 ,text: "XXX", nextId:294},{ id: 314 ,text: "XXX", nextId:288}],
      [{ id: 315 ,text: "XXX", nextId:42},{ id: 315 ,text: "XXX", nextId:342}],
      [{ id: 316 ,text: "XXX", nextId:198}],
      [{ id: 317 ,text: "XXX", nextId:301},{ id: 317 ,text: "XXX", nextId:41}],
      [{ id: 318 ,text: "XXX", nextId:231}],
      [{ id: 319 ,text: "XXX", nextId:228},{ id: 319 ,text: "XXX", nextId:14}],
      [{ id: 320 ,text: "XXX", nextId:362}],
      [{ id: 321 ,text: "XXX", nextId:107}],
      [{ id: 322 ,text: "XXX", nextId:94},{ id: 322 ,text: "XXX", nextId:380}],
      [{ id: 323 ,text: "XXX", nextId:291},{ id: 323 ,text: "XXX", nextId:99},{ id: 323 ,text: "XXX", nextId:102}],
      [{ id: 324, text : "Essayer de casser le vase en le jetant sur le sol ?", nextId:250},{ id: 324, text : "Mettre la main à l'intérieur du vase ?", nextId:161},{ id: 324, text : "Laisser le vase où il est et rejoindre le chemin pour repartir vers le nord", nextId:149}],
      [{ id: 325 ,text: "XXX", nextId:268},{ id: 325 ,text: "XXX", nextId:79}],
      [{ id: 326 ,text: "XXX", nextId:145}],
      [{ id: 327 ,text: "XXX", nextId:351},{ id: 327 ,text: "XXX", nextId:112}],
      [{ id: 328 ,text: "XXX", nextId:118}],
      [{ id: 329 ,text: "XXX", nextId:180},{ id: 329 ,text: "XXX", nextId:252}],
      [{ id: 330 ,text: "XXX", nextId:116}],
      [{ id: 331 ,text: "XXX", nextId:124},{ id: 331 ,text: "XXX", nextId:309}],
      [{ id: 332 ,text: "XXX", nextId:103}],
      [{ id: 333 ,text: "XXX", nextId:0}],
      [{ id: 334 ,text: "XXX", nextId:113},{ id: 334 ,text: "XXX", nextId:51}],
      [{ id: 335 ,text: "XXX", nextId:181},{ id: 335 ,text: "XXX", nextId:326}],
      [{ id: 336 ,text: "XXX", nextId:21},{ id: 336 ,text: "XXX", nextId:108}],
      [{ id: 337 ,text: "XXX", nextId:230},{ id: 337 ,text: "XXX", nextId:358}],
      [{ id: 338 ,text: "XXX", nextId:85},{ id: 338 ,text: "XXX", nextId:358}],
      [{ id: 339 ,text: "XXX", nextId:65},{ id: 339 ,text: "XXX", nextId:75}],
      [{ id: 340 ,text: "XXX", nextId:141},{ id: 340 ,text: "XXX", nextId:347},{ id: 340 ,text: "XXX", nextId:59}],
      [{ id: 341 ,text: "XXX", nextId:149}],
      [{ id: 342 ,text: "XXX", nextId:158},{ id: 342 ,text: "XXX", nextId:11}],
      [{ id: 343 ,text: "XXX", nextId:8},{ id: 343 ,text: "XXX", nextId:239}],
      [{ id: 344 ,text: "XXX", nextId:36}],
      [{ id: 345 ,text: "XXX", nextId:293}],
      [{ id: 346 ,text: "XXX", nextId:32},{ id: 346 ,text: "XXX", nextId:111}],
      [{ id: 347 ,text: "XXX", nextId:363}],
      [{ id: 348 ,text: "XXX", nextId:43},{ id: 348 ,text: "XXX", nextId:188}],
      [{ id: 349 ,text: "XXX", nextId:291},{ id: 349 ,text: "XXX", nextId:102}],
      [{ id: 350 ,text: "XXX", nextId:329}],
      [{ id: 351 ,text: "XXX", nextId:292},{ id: 351 ,text: "XXX", nextId:112}],
      [{ id: 352 ,text: "XXX", nextId:207},{ id: 352 ,text: "XXX", nextId:156}],
      [{ id: 353 ,text: "XXX", nextId:26},{ id: 353 ,text: "XXX", nextId:220}],
      [{ id: 354 ,text: "XXX", nextId:349}],
      [{ id: 355 ,text: "XXX", nextId:340}],
      [{ id: 356 ,text: "XXX", nextId:34},{ id: 356 ,text: "XXX", nextId:395},{ id: 356 ,text: "XXX", nextId:231}],
      [{ id: 357 ,text: "XXX", nextId:306}],
      [{ id: 358 ,text: "XXX", nextId:40},{ id: 358 ,text: "XXX", nextId:218}],
      [{ id: 359 ,text: "XXX", nextId:172},{ id: 359 ,text: "XXX", nextId:281}],
      [{ id: 360 ,text: "XXX", nextId:279},{ id: 360 ,text: "XXX", nextId:104}],
      [{ id: 361 ,text: "XXX", nextId:396},{ id: 361 ,text: "XXX", nextId:86}],
      [{ id: 362 ,text: "XXX", nextId:281},{ id: 362 ,text: "XXX", nextId:238}],
      [{ id: 363 ,text: "XXX", nextId:68},{ id: 363 ,text: "XXX", nextId:59}],
      [{ id: 364 ,text: "XXX", nextId:276},{ id: 364 ,text: "XXX", nextId:194}],
      [{ id: 365 ,text: "XXX", nextId:358}],
      [{ id: 366 ,text: "XXX", nextId:127},{ id: 366 ,text: "XXX", nextId:178}],
      [{ id: 367 ,text: "XXX", nextId:60},{ id: 367 ,text: "XXX", nextId:222}],
      [{ id: 368 ,text: "XXX", nextId:112}],
      [{ id: 369 ,text: "XXX", nextId:191},{ id: 369 ,text: "XXX", nextId:390}],
      [{ id: 370 ,text: "XXX", nextId:231}],
      [{ id: 371 ,text: "XXX", nextId:93}],
      [{ id: 372 ,text: "XXX", nextId:48},{ id: 372 ,text: "XXX", nextId:48},{ id: 372 ,text: "XXX", nextId:288}],
      [{ id: 373 ,text: "XXX", nextId:308},{ id: 373 ,text: "XXX", nextId:148}],
      [{ id: 374 ,text: "XXX", nextId:133},{ id: 374 ,text: "XXX", nextId:360}],
      [{ id: 375 ,text: "XXX", nextId:150},{ id: 375 ,text: "XXX", nextId:236}],
      [{ id: 376 ,text: "XXX", nextId:74},{ id: 376 ,text: "XXX", nextId:310}],
      [{ id: 377 ,text: "XXX", nextId:205},{ id: 377 ,text: "XXX", nextId:92}],
      [{ id: 378 ,text: "XXX", nextId:307},{ id: 378 ,text: "XXX", nextId:67}],
      [{ id: 379 ,text: "XXX", nextId:73},{ id: 379 ,text: "XXX", nextId:112}],
      [{ id: 380 ,text: "XXX", nextId:237},{ id: 380 ,text: "XXX", nextId:144}],
      [{ id: 381 ,text: "XXX", nextId:98}],
      [{ id: 382 ,text: "XXX", nextId:97}],
      [{ id: 383 ,text: "XXX", nextId:254}],
      [{ id: 384 ,text: "XXX", nextId:128},{ id: 384 ,text: "XXX", nextId:394}],
      [{ id: 385 ,text: "XXX", nextId:168},{ id: 385 ,text: "XXX", nextId:313},{ id: 385 ,text: "XXX", nextId:358}],
      [{ id: 386 ,text: "XXX", nextId:119}],
      [{ id: 387 ,text: "XXX", nextId:340}],
      [{ id: 388 ,text: "XXX", nextId:155},{ id: 388 ,text: "XXX", nextId:316}],
      [{ id: 389 ,text: "XXX", nextId:215},{ id: 389 ,text: "XXX", nextId:88}],
      [{ id: 390 ,text: "XXX", nextId:190},{ id: 390 ,text: "XXX", nextId:280}],
      [{ id: 391 ,text: "XXX", nextId:200},{ id: 391 ,text: "XXX", nextId:379}],
      [{ id: 392 ,text: "XXX", nextId:157}],
      [{ id: 393 ,text: "XXX", nextId:369}],
      [{ id: 394 ,text: "XXX", nextId:66},{ id: 394 ,text: "XXX", nextId:186}],
      [{ id: 395 ,text: "XXX", nextId:154},{ id: 395 ,text: "XXX", nextId:370}],
      [{ id: 396 ,text: "XXX", nextId:364},{ id: 396 ,text: "XXX", nextId:96}],
      [{ id: 397 ,text: "XXX", nextId:163},{ id: 397 ,text: "XXX", nextId:393}],
      [{ id: 398 ,text: "XXX", nextId:320},{ id: 398 ,text: "XXX", nextId:193}],
      [{ id: 399, text : "Game Over", nextId:1}],
      [{ id: 400, text : "Game Over", nextId:1}]
];
